In [2]:
import torch
from torch_geometric.data import Data

# shape (2, num_edges)
edge_index = torch.tensor([[0, 1, 1, 2],
                           [1, 0, 2, 1]], dtype=torch.long)
# shape (num_edges, num_edge_features)
edge_attr = torch.tensor([[0.5], [1.0], [1.5], [2.0]], dtype=torch.float)
# shape (num_nodes, num_node_features)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)
# shape (num_nodes, *), 1D or 2D tensor
y = torch.tensor([[-10], [0], [10]], dtype=torch.float)
# shape (num_nodes, num_dim)
pos = torch.tensor([[0, 1], [1, 0], [2, 1]], dtype=torch.float)
data = Data(
    x = x, 
    y = y,
    edge_index=edge_index,
    edge_attr=edge_attr,
    pos=pos
)

edge_index1 = torch.tensor([[0, 1],
                            [1, 0],
                            [1, 2],
                            [2, 1]], dtype=torch.long)
data1 = Data(x = x, edge_index = edge_index1.t().contiguous()) # Transpose and make contiguous is needed

/home/macul/Projects/deep_simulation/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [8]:
(
    data.validate(raise_on_error=True),
    data.keys(),
    data.num_nodes,
    data.num_edges,
    data.num_node_features,
    data.num_edge_features,
    data.has_isolated_nodes(),
    data.has_self_loops(),
    data.is_directed(),
)

(True,
 ['edge_attr', 'x', 'edge_index', 'y', 'pos'],
 3,
 4,
 1,
 1,
 False,
 False,
 True)

In [7]:
for key, item in data:
    print(f'{key}: {item.shape}')

x: torch.Size([3, 1])
edge_index: torch.Size([2, 4])
edge_attr: torch.Size([4, 1])
y: torch.Size([3, 1])
pos: torch.Size([3, 2])


In [3]:
from torch_geometric.utils import scatter
from torch_geometric.datasets import TUDataset
from torch_geometric.loader import DataLoader

dataset = TUDataset(root='/tmp/ENZYMES', name='ENZYMES', use_node_attr=True)
loader = DataLoader(dataset, batch_size=32, shuffle=True)

for data in loader:
    data
    break

Processing...
Done!


In [4]:
data

DataBatch(edge_index=[2, 4766], x=[1255, 21], y=[32], batch=[1255], ptr=[33])

In [5]:
data.x

tensor([[10.0000, 13.9687, 18.2800,  ...,  1.0000,  0.0000,  0.0000],
        [ 9.0000, 11.3767, 30.0700,  ...,  1.0000,  0.0000,  0.0000],
        [ 4.0000,  4.8956, 13.1900,  ...,  1.0000,  0.0000,  0.0000],
        ...,
        [ 4.0000,  9.9716, 13.7800,  ...,  0.0000,  1.0000,  0.0000],
        [ 4.0000, 10.1950, 15.1400,  ...,  0.0000,  1.0000,  0.0000],
        [ 4.0000,  9.8053, 16.9000,  ...,  0.0000,  1.0000,  0.0000]])

In [ ]:
data.edge_index # node idx in this batch

tensor([[   0,    0,    0,  ..., 1254, 1254, 1254],
        [   1,   16,   17,  ..., 1245, 1252, 1253]])

In [ ]:
data.batch # graph idx for each node in the batch

tensor([ 0,  0,  0,  ..., 31, 31, 31])

In [2]:
import torch
torch.__version__

'2.10.0+cu128'